extends: default

rules:
  comments:
    ignore: .github/workflows/
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length: disable
  truthy:
    ignore: .github/workflows/
