---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nova-api
  namespace: openstack
spec:
  name: "nova_api"
  mariaDbRef:
    name: mariadb  # name of the MariaDB kind
    waitForIt: true
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: nova-api-grant
  namespace: openstack
spec:
  mariaDbRef:
    name: mariadb  # name of the MariaDB kind
    waitForIt: true
  privileges:
    - "ALL"
  database: "nova_api"
  table: "*"
  username: nova
  grantOption: true
  host: "%"
  retryInterval: 5s
