---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dex
  target:
    name: grafana-sso
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: grafana-sso
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
