---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudnative-postgres-nautobot.yaml
  - secretstore-nautobot.yaml
  - external-secret-nautobot-sso.yaml

configMapGenerator:
  - name: dexauth
    files:
      - dexauth.py
    options:
      disableNameSuffixHash: true
