---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neutron-svc-user
  namespace: argo-events
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - list
  - get
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neutron-svc-user
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neutron-svc-user
subjects:
- kind: ServiceAccount
  name: neutron-server
  namespace: openstack
