# Full documentation available at
# https://github.com/dexidp/helm-charts/tree/master/charts/dex#values
#
# This file is intended to be combined with the values-generic.yaml
# connectors is a list which must be duplicated since helm won't merge

config:
  connectors:
    - type: oidc
      name: Azure
      id: azure
      config:
        issuer: $OIDC_ISSUER
        clientId: $OIDC_CLIENT_ID
        clientSecret: $OIDC_CLIENT_SECRET
        redirectURI: $OIDC_REDIRECT_URI
        scopes:
          - openid  # required for OIDC
          - profile  # provides the "preferred_username" key which some services need
          - email
          - offline_access
        insecureSkipEmailVerified: true
        insecureEnableGroups: true
        getUserInfo: true
        claimMapping:
          groups: "roles"
