apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- appsets/infra.yaml
- appsets/argocd-operators-project.yaml
- appsets/operators.yaml
- appsets/components.yaml
- appsets/openstack.yaml
